# uv tool install pre-commit
# pre-commit
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # pin the same version as in pyproject.toml
    rev: v0.16.10
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        # entry: uv run pyright
        entry: /bin/sh -c 'export PATH="$HOME/.local/bin:/opt/homebrew/bin:/usr/local/bin:$PATH"; exec uv run --no-sync pyright'
        language: system
        pass_filenames: false
        types: [python]
