[project]
name = "aiolocust"
version = "0.0.0" # updated from github action on tags
description = "High performance Python-based load testing tool"
requires-python = ">=3.14"
dependencies = [
    "aiohttp>=3.14.0",
    "rich>=14.2.0",
    "uvloop>=0.22.1 ; sys_platform == 'linux'",
    "uvloop>=0.22.1 ; sys_platform == 'darwin'",
    "typer>=0.21.1",
    "opentelemetry-api>=1.40.0",
    "opentelemetry-sdk>=1.40.0",
    "opentelemetry-instrumentation-aiohttp-client>=0.61b0",
    "opentelemetry-instrumentation-logging>=0.61b0",
    "click>=8.4.0",
    "pyrate-limiter>=4.5.0",
]
readme = "README.md"
authors = [{ name = "Lars Holmberg", email = "lars.holmberg@redshirt.se" }]
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "Topic :: Software Development :: Testing",
    "Topic :: Software Development :: Testing :: Traffic Generation",
]

[tool.uv]
package = true

[build-system]
requires = ["uv_build>=0.11.0,<0.13.0"]
build-backend = "uv_build"

[tool.ruff]
target-version = "py314"
line-length = 120
lint.ignore = ["E501", "E402", "E713", "E731"]
lint.select = ["E", "F", "W", "UP", "I", "ARG001"]
lint.dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?)|resp)$"

[dependency-groups]
dev = [
    "mkdocs-click>=0.9.0",
    "mkdocs-material>=9.7.6",
    "mkdocstrings[python]>=1.0.3",
    "pyright==1.1.414",
    "pytest>=9.0.3",
    "pytest-aiohttp>=1.1.0",
    "pytest-asyncio>=1.3.0",
    "pytest-httpserver>=1.1.3",
    "pytest-mock>=3.15.1",
    "pytest-timeout>=2.4.0",
    "ruff>=0.15.5",
]

[project.scripts]
aiolocust = "aiolocust.main:app"

[project.optional-dependencies]
pymongo = [
    "pymongo>=4.16.0",
]

[tool.pytest]
filterwarnings = ["ignore:Inheritance class LocustClientSession from ClientSession is discouraged:DeprecationWarning"]
asyncio_mode = "auto"

[tool.pyright]
typeCheckingMode = "strict"
reportMissingTypeArgument = false
reportUnknownParameterType = false
reportUnknownArgumentType = false
reportMissingParameterType = false
reportPrivateUsage = false
reportUnknownMemberType = false
reportUnknownVariableType = false
reportMissingTypeStubs = false

[[tool.pyright.executionEnvironments]]
root = "tests"
reportUnusedVariable = false

[[tool.pyright.executionEnvironments]]
root = "examples/testdata_from_mongodb.py"
reportUnusedVariable = false
reportMissingImports = false
